# Generated by Django 5.1.7 on 2025-03-22 16:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('alternative_number', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('qualifications', models.CharField(max_length=255)),
                ('married_status', models.BooleanField(default=False)),
                ('current_address', models.TextField()),
                ('landmark', models.CharField(max_length=255)),
                ('years_at_address', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('office_name', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('current_experience', models.IntegerField()),
                ('overall_experience', models.IntegerField()),
                ('reference_name_1', models.CharField(max_length=255)),
                ('reference_number_1', models.CharField(max_length=15)),
                ('reference_name_2', models.CharField(max_length=255)),
                ('reference_number_2', models.CharField(max_length=15)),
                ('expected_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.TextField()),
                ('client_type', models.CharField(choices=[('direct', 'Direct Client'), ('employee_registered', 'Employee-Registered Client')], default='direct', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cibil_score', models.IntegerField()),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('cibil_report', models.ImageField(blank=True, null=True, upload_to='documents/cibil/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='documents/pan/')),
                ('gas_bill', models.ImageField(blank=True, null=True, upload_to='documents/gas/')),
                ('reference_number_1', models.CharField(max_length=15)),
                ('reference_number_2', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_details', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.user'),
        ),
    ]
